"""D2-1: official part fidelity matrix — for each snapshotted official
<parts> element, part_params -> set_part_params round-trip must preserve
the official key values (numeric equivalence for floats, exact text for
strings).  Fixtures regenerated by tools/snapshot_official_parts.py."""
from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import pytest

from cabxml import PropertyModel, StpreModel, new_property_bytes, \
    new_stpre_bytes, parse_property, parse_stpre

_SPEC = StpreModel._SPECIAL_PARAM_FIELDS

FIX = Path(__file__).resolve().parent / "fixtures" / "official_parts"
SNAPSHOTS = sorted(FIX.glob("*.xml"))


def _model_with(snapshot: Path):
    import xml.etree.ElementTree as ET
    m = StpreModel(parse_stpre(new_stpre_bytes("T")))
    el = ET.fromstring(snapshot.read_text(encoding="utf-8"))
    m.root.append(el)
    return m, el


def _close(a, b) -> bool:
    try:
        return abs(float(a) - float(b)) < 1e-9
    except (TypeError, ValueError):
        return str(a).strip() == str(b).strip()


@pytest.mark.parametrize("snap", SNAPSHOTS, ids=lambda p: p.stem)
def test_official_part_param_fidelity(snap):
    m, el = _model_with(snap)
    name = el.findtext("name").strip()
    kind = snap.stem.split("__")[0]
    spec = _SPEC[kind]
    before = m.part_params(name)
    assert before, f"{snap.stem}: no managed params stored"
    # write the exact same values back
    assert m.set_part_params(name, dict(before))
    after = m.part_params(name)
    for key, spec_item in spec.items():
        fmt = spec_item[1]
        if key not in before:
            continue
        b, a = before[key], after[key]
        if fmt == "str":
            assert str(a).strip() == str(b).strip(), \
                f"{snap.stem}.{key}: {b!r} -> {a!r}"
        else:
            bl = b if isinstance(b, list) else [b]
            al = a if isinstance(a, list) else [a]
            assert len(bl) == len(al), \
                f"{snap.stem}.{key}: arity {len(bl)} -> {len(al)}"
            for x, y in zip(bl, al):
                assert _close(x, y), \
                    f"{snap.stem}.{key}: {x} -> {y}"


def test_matrix_covers_seven_official_kinds():
    kinds = {p.stem.split("__")[0] for p in SNAPSHOTS}
    assert {"peltier", "axial_fan", "two_resistor", "plate_fin",
            "panel", "sphere", "enclosure"} <= kinds


def test_two_resistor_bridge_fidelity():
    """Official condition nodes survive the parameter round-trip
    (resistance unit attrs + node mapping)."""
    snaps = sorted(FIX.glob("two_resistor__*.xml"))
    for snap in snaps:
        m, el = _model_with(snap)
        name = el.findtext("name").strip()
        before = m.part_params(name)
        assert m.set_part_params(name, dict(before))
        cond = el.find("condition")
        if cond is None:
            continue
        for res in cond.findall("resistance"):
            assert res.attrib.get("unit") == "K/W"
        params = m.part_params(name)
        for key in ("rjc", "rjb", "package_power"):
            if key in before:
                assert _close(before[key], params[key]), key
